superlists/lists/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^(.+)/$','lists.views.view_list',name='view_list'),
    url(r'^new$', 'lists.views.new_list', name='new_list'),
)

superlists/superlists/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
)

superlists/lists/models.py
from django.db import models

class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField()
    list = models.ForeignKey(List)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.text

superlists/lists/forms.py
from django import forms

from lists.models import Item

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].error_messages['required'] = EMPTY_LIST_ERROR

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={'placeholder': 'Enter a to-do item'}
            ),
        }

class ExistingListItemForm(ItemForm):

    class Meta(ItemForm.Meta):
        fields = ('list','text')

    def validate_unique(self):
        super().validate_unique()
        if self.non_field_errors():
            self._update_errors({'text': [DUPLICATE_ITEM_ERROR]})
            del self.errors['__all__']

superlists/lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError

from lists.forms import ItemForm
from lists.models import Item, List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, list_id):
    list = List.objects.get(id=list_id)
    error = None

    if request.method == 'POST':
        try:
            Item.objects.create(text=request.POST['text'], list=list)
            return redirect('/lists/%d/' % (list.id,))
        except ValidationError as e:
            if 'blank' in str(e):
                error = "You can't have an empty list item"
            elif 'already exists' in str(e):
                error = "You've already got this in your list"

    return render(request, 'list.html', {'list': list, "error": error})

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list = List.objects.create()
        Item.objects.create(text=request.POST['text'], list=list)
        return redirect('/lists/%d/' % (list.id,))
    else:
        return render(request, 'home.html', {"form":form})

superlists/lists/templates/base.html
<html>
	<head>
		<title>To-Do lists</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
		<link href="/static/base.css" rel="stylesheet" media="screen">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="span8 offset2">
					<div class="hero-unit">
						<div class="text-center">
							<h1>{% block header_text %}{% endblock %}</h1>
							{% block form %}
							{% endblock %}
						</div>
						{% block table %}
						{% endblock %}
					</div>
				</div>
			</div>
		</div>
		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="/static/bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>

superlists/lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}Start a new To-Do list{% endblock %}
{% block form %}
	<form method="POST" action="/lists/new" >
		{{ form.text }}
		{% csrf_token %}
		{% if form.errors %}
			<div class="alert alert-error">{{ form.text.errors }}</div>
		{% endif %}
	</form>
{% endblock %}

superlists/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form %}
	<form method="POST" action="/lists/{{ list.id }}/" >
		<input name="text" id="id_text" placeholder="Enter a to-do item" />
		{% csrf_token %}
		{% if error %}
			<p class="alert alert-error">{{ error }}</p>
		{% endif %}
	</form>
{% endblock %}

{% block table %}
	<table id="id_list_table" >
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}